close_when_open = true
theme = "ima"
theme_location = ["~/.config/walker/themes/"]
hotreload_theme = true
force_keyboard_focus = true

[keys.ai]
run_last_response = ["ctrl e"]

[events]
on_activate = ""
on_selection = ""
on_exit = ""
on_launch = ""
on_query_change = ""

[list]
max_entries = 200

[search]
placeholder = "Search..."

[builtins.hyprland_keybinds]
path = "~/.config/hypr/hyprland.conf"
hidden = true

[builtins.applications]
placeholder = "Applications"
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
icon = ""
hidden = true

[builtins.applications.actions]
enabled = false
hide_category = true

[builtins.bookmarks]
hidden = true

[[builtins.bookmarks.entries]]
label = "Walker"
url = "https://github.com/abenz1267/walker"
keywords = ["walker", "github"]


[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3
prefix = "="

[builtins.windows]
switcher_only = true
hidden = true

[builtins.clipboard]
hidden = true

[builtins.commands]
hidden = true

[builtins.custom_commands]
hidden = true

[builtins.emojis]
name = "emojis"
icon = ""
prefix = ":"

[builtins.symbols]
after_copy = ""
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = false
hidden = false

[builtins.runner]
shell_config = ""
switcher_only = true
hidden = true

[builtins.ssh]
hidden = true

[builtins.websearch]
switcher_only = true
hidden = true

[builtins.translation]
hidden = true
